# These params are needed for / used by all the model types

# Possible values are string values of [RACE_PP, RACE_PP_4K, RACE_PP_8K, RACE_PP_12K, ARC, ARC_BALANCED, AM]
dataset_name: race_4000
# Possible values are [r2de, text2props, random, majority, transformer]
model_type: transformer
# If desired, it is possible to specify the name used to save the model.
model_name: DistilBERT
regression: false
num_labels: 2

# # # # #

# If given, it is used by all model types except but majority
random_seed: 123

# # # # #

# Specific for Transformer
input_mode: question_all
pretrained_model: distilbert-base-uncased
max_length: 256
pretrained_tokenizer: null
epochs: 3
batch_size: 16
eval_batch_size: 128
early_stopping_patience: 5
learning_rate: 0.00002  # 2e-5
weight_decay: 0.01
